// Monster TRUE LEVELS (viLevel) extracted from kod source
// (kod/object/.../battler/monster/*.kod). Ground truth for target
// banding: known level first, HP proxy only as fallback. Keys are
// mobNameKey-normalized (token-sorted) display names.
export const MONSTER_LEVELS = {
  "angel dark": 200,
  "ant": 40,
  "ant mutant": 65,
  "army duke of s soldier the": 50,
  "army of princess soldier the": 50,
  "avar chieftain peet seeeep": 135,
  "avar peet seeeep shaman": 100,
  "avar peet seeeep warrior": 120,
  "baby spider": 25,
  "battered skeleton": 60,
  "beast fungus": 50,
  "black spider": 75,
  "body boss of orc pit the": 1,
  "boss orc pit": 115,
  "bramble of patch": 25,
  "cave orc": 80,
  "centipede": 30,
  "cow": 200,
  "cow guard": 100,
  "creature ice": 90,
  "creature mollusk": 150,
  "cyr ghostly of queen remains venya": 200,
  "cyr queen venya": 200,
  "daemon skeleton": 130,
  "diseased tree": 50,
  "dragonfly": 120,
  "dragonfly pet": 120,
  "dragonfly queen": 145,
  "dusk rat": 50,
  "eating man plant": 60,
  "elhai fey": 60,
  "evil twin": 1,
  "faction troop": 80,
  "frogman": 70,
  "ghost": 200,
  "giant rat": 30,
  "giant scorpion": 55,
  "groundworm": 100,
  "groundworm larva": 35,
  "groundworm queen": 130,
  "king lupogg": 200,
  "kriipa": 160,
  "living tree": 50,
  "lupogg": 105,
  "ma xeochicatl": 190,
  "mummy": 25,
  "mummy spectral": 40,
  "narthyl worm": 120,
  "necromancer": 60,
  "orc": 45,
  "orc wizard": 80,
  "queen spider": 165,
  "rat snow": 60,
  "rebel soldier": 50,
  "reflection": 45,
  "revenant": 55,
  "ro xeochicatl": 170,
  "shadowbeast": 200,
  "skeleton": 75,
  "skeleton tusked": 100,
  "slime": 35,
  "spider": 50,
  "statue": 75,
  "stntroll": 120,
  "te xeochicatl": 200,
  "teotimixlal": 60,
  "thrasher": 150,
  "troll": 90,
  "ve xeochicatl": 150,
  "xeochicatl": 150,
  "yeti": 170,
  "zombie": 55
};
export function knownLevel(name, keyOf) { const k = (keyOf ?? ((s)=>String(s??"").toLowerCase()))(name); return MONSTER_LEVELS[k] ?? null; }
